mode: ContinuousDeployment
tag-prefix: '[vV]'
commit-message-incrementing: MergeMessageOnly
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch
version-in-branch-pattern: (?<version>[vV]?\d+(\.\d+)?(\.\d+)?).*
major-version-bump-message: "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\\([\\w\\s-,/\\\\]*\\))?(!:|:.*\\n\\n((.+\\n)+\\n)?BREAKING CHANGE:\\s.+)"
minor-version-bump-message: "^(feat)(\\([\\w\\s-,/\\\\]*\\))?:"
patch-version-bump-message: "^(fix|perf)(\\([\\w\\s-,/\\\\]*\\))?:"
no-bump-message: \+semver:\s?(none|skip)
tag-pre-release-weight: 60000
commit-date-format: yyyy-MM-dd
update-build-number: true
branches:
  hotfix:
    mode: ContinuousDelivery
    label: 'hotfix'
    regex: hotfix[/-]
    source-branches: ['main']
  feature:
    mode: ContinuousDelivery
    label: 'alpha'
    increment: Minor
    regex: feature[/-]
  main:
    mode: ContinuousDeployment
    is-main-branch: true
    increment: Patch
    regex: main|master$
    pre-release-weight: 30000
    prevent-increment:
      of-merged-branch: true
      when-current-commit-tagged: true